### ISSUE TITLE
In depth example please

### ISSUE THREAD

**Issue by NobrainerWeb** [markguinn/silverstripe-gridfieldmultiselect#1]
Can you add som more in depth info on how to use the module?
I am trying to use a custom action, but i'm unable to make it work.
The checkboxes are added to the GF, the button is also showing and clicking it makes the GF reload, but my custom action seems to do nothing.

```
$gridField->getConfig()->addComponents(
	new GridFieldCheckboxSelectComponent(),
	new GridFieldApplyToMultipleRows(
		'markAsPaid',
		'Mark as paid',
		function($record, $index){
			$record->markAsPaid();
		}
	)
);
```
markAsPaid is a method on my GF managed DO, that just sets a boolean to true.
Can you make a simple, but complete example for using a custom action please?

Btw: this module is going to be so usefull. Modules that enhances the usabilty of the CMS are super :-)

**Comment by markguinn** [comment]
This looks correct to me. The only difference in the way I'm using it in my app is like so:

```
	/**
	 * @param Form $form
	 */
	public function updateEditForm(&$form) {
		/** @var GridField $gridField */
		$gridField = $form->Fields()->fieldByName('Order');
		$gridConfig = $gridField->getConfig();
		$gridConfig->addComponents(
			new GridFieldCheckboxSelectComponent(),
			new GridFieldMultiDeleteButton(),
			new GridFieldApplyToMultipleRows('billing', 'Export For Billing', array($this, 'exportRowForBilling'))
		);
	}


	/**
	 * @param Order $record
	 * @param int $index
	 */
	public function exportRowForBilling($record, $index) {
		$record->BillingExportDate = date('Y-m-d');
		$record->write();
	}
```

Which should be equivalent just without using a closure. I'd do some logging/debugging to verify that the markAsPaid method is actually being called. Thanks.

**Comment by NobrainerWeb** [comment]
Thanks for your quick response.
Are your two functions in the same file?
And gridfieldApplyToMRows params should be defined as?

**Comment by NobrainerWeb** [comment]
Btw, are you using that in a crm project? 
Cause that is what i'm working on (very simple though)

**Comment by markguinn** [comment]
They are in the same file, same class. No, this is for a fairly large e-commerce site. Good luck!

**Comment by NobrainerWeb** [comment]
Thank you for the module and your help.
Everything works as expected now - i think i was not flushing when testing, so i had some unexpected results.
